### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by bobbysebolao** [ReginaldJbeili/feline-fun-mr-project#18]
Congratulations on building a really fun project! 🚀 🎸 ⚡️  You've done a smashing job getting all your cats in a row to make something meow-vellous! This week covers such a lot of new concepts and design patterns, well done for embracing the change!

If you have time today, you have a solid foundation here to build upon and implement the cat feeding functionality that you planned 🐱 🐭 😋

![cats](https://media0.giphy.com/media/Maz1hoeGskARW/giphy.gif?cid=790b76117f7f33f301c2a099c1e22ccb17db49830f70fe78&rid=giphy.gif)

**Comment by ReginaldJbeili** [comment]
Cat feeding functionality and button design done!
