### ISSUE TITLE
ES6 Destructuring of props object

### ISSUE THREAD

**Issue by bobbysebolao** [ReginaldJbeili/feline-fun-mr-project#20]
In App.js (lines 14-16) you have the right idea about needing to access the individual properties inside of the props object:

```

    const catEnergy = props.catEnergy
    const setCatEnergy = props.setCatEnergy
    const selectedCat = props.selectedCat

```

👏 👏 👏 

There is a neater way to do this using ES6 object destructuring:

```

const { catEnergy, setCatEnergy, selectedCat } = props

```

Destructuring like this extracts each of the specified properties from an object and declares it as a variable. It lets you access the properties without the props. prefix. It is arguably a bit easier to read (esp. if you have a big props object to deal with).

**Comment by ReginaldJbeili** [comment]
destructuring done
