### ISSUE TITLE
Count down functionality in EnergyMetre

### ISSUE THREAD

**Issue by bobbysebolao** [ReginaldJbeili/feline-fun-mr-project#21]
Kudos for getting the timer to count down! (this is something I really struggled with in my React week project) You’ve used setInterval correctly to update the state. 

Also well done for knowing to pass in the prevCountState argument in order to check when the counter has hit zero! 

![more cats](https://media1.giphy.com/media/13UKMgwNHrBSIo/giphy.gif?cid=790b76119854dffd3b39aa20d2db853adde1613f5c050989&rid=giphy.gif)

**Comment by ReginaldJbeili** [comment]
Thank you. We added a progress bar as well
