### ISSUE TITLE
Use React.Fragment instead of <div>

### ISSUE THREAD

**Issue by bobbysebolao** [ReginaldJbeili/feline-fun-mr-project#22]
As you’ve correctly identified in Catinfo.js and CatDropdown.js, when you return multiple JSX child elements from a component, you need to wrap them inside of a single containing element. Well done!

```
return (
    <div>
      <h1>{props.catInfo[0].breeds[0].name}</h1>
      <p>{props.catInfo[0].breeds[0].description}</p>
…
    </div>
  );

```

Instead of wrapping them in a div, you can use a built in feature of React called a <React.Fragment> to enclose everything:

```
return (
    <React.Fragment>
      <h1>{props.catInfo[0].breeds[0].name}</h1>
      <p>{props.catInfo[0].breeds[0].description}</p>
…
    </React.Fragment>
  );


```

React Fragments don’t get added to the DOM (unlike divs), so they're neater and better semantically.

**Comment by ReginaldJbeili** [comment]
noted thanks!
